pipeline {
	agent {
		kubernetes {
			label "java"
		}
	}

	environment {
		ANT_OPTS = "-Xmx2560m"
		LABEL_BUILD_DATE = "${sh(script: "date -u +%Y-%m-%dT%H:%M:%SZ", returnStdout: true).trim()}"
		IMAGE_NAME = "liferaycloud/com-liferay-osb-faro"
		IMAGE_TAG_SUFFIX = "${FARO_ENVIRONMENT}-${sh(script: "date +%Y%m%d", returnStdout: true).trim()}-${sh(script: "git rev-parse --short=7 ${GIT_COMMIT}", returnStdout: true).trim()}"
		JAVA_HOME = "/opt/java/jdk8u292-b10"

		DOCKER_BUILD_ARGS = "--build-arg LABEL_BUILD_DATE=${LABEL_BUILD_DATE} --build-arg LABEL_VCS_REF=${GIT_COMMIT} --no-cache -f ./Dockerfile ./"
	}

	stages {
		stage("Build") {
			steps {
				withCredentials([
					string(credentialsId: 'analytics_cloud_ci_ssh', variable: 'SECRET'),
					string(credentialsId: 'analytics_cloud_faro_license', variable: 'LICENSE'),
					[$class: 'UsernamePasswordMultiBinding', credentialsId: 'liferay-nexus-repository-credentials', usernameVariable: 'NEXUS_USERNAME', passwordVariable: 'NEXUS_PASSWORD']
				]) {
					sh '''
						echo "Nexus Username ${NEXUS_USERNAME}"
						echo "Nexus Password ${NEXUS_PASSWORD}"

						
					'''
                }
			}
		}

		stage("Build Docker Image") {
			steps {
				dir("modules/dxp/apps/osb/osb-faro/osb-faro-docker/cloud") {
					
				}
			}
		}
	}
}